apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-updater-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: config-updater-sa
  namespace: default
roleRef:
  kind: Role
  name: config-updater-role
  apiGroup: rbac.authorization.k8s.io
