apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-traffic-network
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ipvlan",
    "master": "ens5",
    "mode": "l2",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.72.128/26",
      "rangeStart": "192.168.72.130",
      "rangeEnd": "192.168.72.190",
      "gateway": "192.168.72.129"
    }
  }'
