apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-ip-cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-ip-cu
  template:
    metadata:
      labels:
        app: oai-ip-cu
    spec:
      serviceAccountName: config-updater-sa
      containers:
      - name: oai-ip-cu
        image: krsnucc21/config-updater
        env:
        - name: NODE_TYPE
          value: "cu" # Set this to "du" for the du pod
        - name: IP_CONFIGMAP_NAME
          value: "oai-ip-config"
        - name: GNB_CONFIGMAP_NAME
          value: "cu-config" # Set this to "du" for the du pod
        - name: CONFIGMAP_NAMESPACE
          value: "default" # Change if your ConfigMap is in a different namespace
